import os
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from graph.state import GraphState, AdData, EnhancedHeroResult, ValidationResult

def hero_enhance_node(state: GraphState) -> dict:
    """
    Agent 3: Personalise hero HTML to match ad creative.
    On retries, injects the validator's critique into the prompt.
    """
    ad_data: AdData = state["ad_data"]
    hero_html = state["hero_html_chunk"]
    retry_count = state.get("retry_count", 0)
    validation_result = state.get("validation_result")

    # Build the base prompt
    system_prompt = f"""You are an expert CRO specialist and frontend developer.

TASK: Identify specific text strings in the provided Hero HTML that must be replaced to create strong message match with the ad creative.

AD CREATIVE DATA:
Headline: {ad_data.headline}
Offer: {ad_data.offer}
Tone: {ad_data.tone}

WHAT YOU MUST DO:
- Output a list of text replacements.
- For 'original_text', copy the EXACT text string from the HTML (e.g. the H1 text, button text, or paragraph text). Copy it exactly character-for-character.
- For 'new_text', provide the new personalized message.
- If the ad has a specific offer NOT present in the text, provide 'offer_banner_text' which will be injected as a banner at the top automatically.

STRICT RULES:
1. ONLY extract visible text. Never include HTML tags in 'original_text'.
2. Tone must be: {ad_data.tone}
3. Do NOT invent claims not supported by the ad data.
"""

    if retry_count > 0 and validation_result and validation_result.critique:
        system_prompt += f"""\n\nIMPORTANT — THIS IS RETRY #{retry_count}:
Your previous output failed validation. The validator's critique:
{validation_result.critique}

Fix the specific issues mentioned above. Do not repeat the same mistakes."""

    llm = ChatOpenAI(
        model=state.get("llm_model", "google/gemini-3.1-flash-lite-preview"),
        api_key=os.environ.get("OPENROUTER_API_KEY"),
        base_url="https://openrouter.ai/api/v1",
        temperature=0.1
    )

    try:
        structured_llm = llm.with_structured_output(EnhancedHeroResult)
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=f"Hero HTML to personalise:\n\n{hero_html}\n\nProvide the text replacements.")
        ]
        
        result = structured_llm.invoke(messages)

        # Execute safe surgical Python string replacement
        enhanced_html = hero_html
        
        for r in result.replacements:
            orig = r.original_text.strip()
            new_text = r.new_text.strip()
            if orig and orig in enhanced_html:
                enhanced_html = enhanced_html.replace(orig, new_text, 1)
            else:
                # Try finding it exactly as the LLM provided if strip() messed up formatting
                if r.original_text in enhanced_html:
                    enhanced_html = enhanced_html.replace(r.original_text, new_text, 1)

        # Inject banner if requested
        if result.offer_banner_text:
            from bs4 import BeautifulSoup
            soup = BeautifulSoup(enhanced_html, "lxml")
            
            banner_html = f'<div class="ad-personalizer-banner" style="background:#111;color:#fff;border:1px solid #333;padding:12px 24px;text-align:center;font-weight:600;margin-bottom:16px;">{result.offer_banner_text}</div>'
            banner_soup = BeautifulSoup(banner_html, "lxml").div
            
            # Find the most reasonable top-level container in the hero chunk, or just prepend
            container = soup.find()
            if container:
                # If there's a body tag generated by lxml, insert into it, otherwise insert directly
                if soup.body and container.name == 'html':
                    soup.body.insert(0, banner_soup)
                else:
                    container.insert(0, banner_soup)
            
            enhanced_html = str(soup)

        return {
            "enhanced_hero_html":  enhanced_html,
            "enhancement_result":  result,
            "retry_count": retry_count + 1,
            "processing_steps": state.get("processing_steps", []) + [f"hero_enhancer: complete (attempt {retry_count + 1})"]
        }
    except Exception as e:
         return {
             "error": f"Hero enhancement failed: {str(e)}",
             "processing_steps": state.get("processing_steps", []) + [f"hero_enhance error: {str(e)}"]
         }
